#!/bin/sh

# Format string to json array
command=`echo " "$4 | sed -r "s/ ([^ ]+)/ \"\\1\",/g"`

# Remove last character
command=`echo $command | sed 's/.$//'`

# echo $command

aws ecs run-task --cluster $1 --task-definition $2 --overrides "{\"containerOverrides\": [{\"name\": \"$3\", \"command\": [$command]}]}"
